sudo: false

language: node_js

before_script:
  - npm run build

node_js:
- '10'
- '11'
- '12'
- '13'

matrix:
  include:
  - node_js: '10'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: '10'
    env: BROWSER_NAME=chrome BROWSER_VERSION=29
  - node_js: '10'
    env: BROWSER_NAME=firefox BROWSER_VERSION=latest
  - node_js: '10'
    env: BROWSER_NAME=opera BROWSER_VERSION=latest
  - node_js: '10'
    env: BROWSER_NAME=safari BROWSER_VERSION=latest
  - node_js: '10'
    env: BROWSER_NAME=safari BROWSER_VERSION=7
  - node_js: '10'
    env: BROWSER_NAME=safari BROWSER_VERSION=6
  - node_js: '10'
    env: BROWSER_NAME=safari BROWSER_VERSION=5
